name: Linter

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to be used.'
        required: true
        type: string
      node-version:
        description: 'Node.js version to be used.'
        required: false
        type: string
      commit-changes:
        description: 'Whether to automatically commit linting changes'
        required: false
        type: boolean
        default: false
    secrets:
      composer-auth:
        description: 'Credentials used to access private Composer repositories'
        required: false

permissions:
  contents: write

jobs:
  linter:
    name: Linter

    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Confirm Versions
        run: |
          php --version
          composer --version
          echo "NPM Version: $(npm --version)"
          echo "Node Version: $(node --version)"
          echo "NPX Version: $(npx --version)"

      - name: Install Node.js Dependencies
        run: npm ci --no-scripts

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: ' -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist'
        env:
          COMPOSER_AUTH: ${{ secrets.composer-auth }}

      - name: Run Laravel Pint
        run: vendor/bin/pint

      - name: npm run format
        run: npm run format

      - name: npm run lint
        run: npm run lint

      - name: Commit Changes
        if: ${{ inputs.commit-changes }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style
          commit_options: '--no-verify'
